### PR TITLE
Configure server.rs to accept address and port (#23)

### LINKED ISSUE #23: Make port and server address configurable
Right now when `cargo run` is executed, the server is started bound to address `0.0.0.0` and port 8080. Those two values should be configurable via command line arguments.

Changing the port would allow two instances running on the same machine.

Changing the address would allow supporting IPv6 or limiting connections to localhost.

Maybe the library `clap` could be used.

### PR DESCRIPTION
**Pull request by th3oth3rjak3**
Also add `clap` to parse cli args.

This fixes #23

### CODE REVIEW

**Comment by carsten-wenderdel** [comment]
This looks good, thanks a lot!

One detail however: When `cargo run` is executed without arguments, the following is printed to the command line:

```
You can access the server for example via
http://0.0.0.0:8080/move?die1=3&die2=1&p24=2&p19=-5&p17=-3&p13=5&p12=-5&p8=3&p6=5&p1=-2
http://0.0.0.0:8080/swagger-ui
```

Those links don't work, at least not in my browser.

Maybe we could print out `localhost` instead of `0.0.0.0` if no argument for `address` is given? Or maybe we use `127.0.0.1` as default address instead?

**Comment by th3oth3rjak3** [comment]
Oh, interesting, yeah they're not working for me either. I think you're right that a good default would be 127.0.0.1 for local development.  When deployed to production would you want these links to show up in the logs? I'll play around a bit and see if I can come up with a flexible solution.

**Comment by carsten-wenderdel** [comment]
Regarding logs in production - I would keep it simple for now. Unless @tslocum has some special requests - he is currently the only one who has `server.rs` in production.

**Comment by carsten-wenderdel** [comment]
Nice, thank you!

**Pull request merged**
